name: devops 

on: 
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: List Files
        run: |
          echo  "Listing files in the repository"

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest 
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name:  Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push Docker image
        run: |
          echo "Building and pushing Docker image"
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops:${{ github.sha }}